name: CI

on:
  push:
    branches:
      - 'master'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Gradle Build
        run: |
          bin/build.sh
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          path: |
            ./build/libs/quiz*.jar
          if-no-files-found: error
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            jcamiel/quiz:latest
            ghcr.io/jcamiel/quiz:latest

